import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Link from "next/link";
import {Suspense} from "react";
import LoadingPage from "./loading";
const inter = Inter({subsets: ["latin"]});
import SearchProvider from "@/context/SearchProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="ko">
      <body className={`${inter.className} mx-auto max-w-xl`}>
        <nav>
          <ul className="flex gap-4">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/search"}>SearchPage</Link>
            </li>
          </ul>
        </nav>

        <SearchProvider>
          <Suspense fallback={<LoadingPage />}>{children}</Suspense>
        </SearchProvider>
      </body>
    </html>
  );
}
