import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";

import Link from "next/link";
import {Suspense} from "react";
import LoadingPage from "./loading";
const inter = Inter({subsets: ["latin"]});
import {RecoilRoot} from "recoil";
import SearchProvider from "@/context/SearchProvider";
import FloatingButton from "@/components/FloatingButton/FloatingButton";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="ko">
      <body className={`${inter.className} mx-auto max-w-xl`}>
        <nav>
          <ul className="flex gap-4">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/search"}>SearchPage</Link>
            </li>
          </ul>
        </nav>
        <div style={{border: "2px solid blue", padding: "0", height: "calc(100vh - 24px )", position: "relative", overflow: "auto"}}>
          <SearchProvider>{children}</SearchProvider>
          <FloatingButton />
        </div>
      </body>
    </html>
  );
}
